### ISSUE TITLE
Error: Failed to install 'jsmp' from GitHub:

### ISSUE THREAD

**Issue by Andrzej-Andrzej** [ymer/jsmp#1]
Hi,
I receive this message: Multiple results for CXX11FLAGS found, something is wrong.FALSE

how to solve it and install your package ? I am on win 10  x64

**Comment by ymer** [comment]
Hi

The package loads all the other packages that are regularly useful in rstats. Maybe you could try and install them, the problem may stem from one of those.

They are:
	tidyverse,
	magrittr,
	gt,
	scales,
	stringr,
	patchwork,
	broom,
	glue,
	lubridate,
	pander
	snakecase
	
Best

**Comment by Andrzej-Andrzej** [comment]
Thank you anyway, but there is a solution here:
[https://github.com/stan-dev/rstan/issues/866](url)

I removed duplicated etries as suggested. 
best
